package com.rag.chat.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response object from the RAG system")
public class QueryResponse {
    
    @Schema(
        description = "The answer generated by the RAG system",
        example = "The main topic of the document is artificial intelligence and machine learning."
    )
    private String answer;
    
    @Schema(
        description = "Status of the request",
        example = "success",
        allowableValues = {"success", "error"}
    )
    private String status;
    
    public QueryResponse() {}
    
    public QueryResponse(String answer, String status) {
        this.answer = answer;
        this.status = status;
    }
    
    public String getAnswer() { return answer; }
    public void setAnswer(String answer) { this.answer = answer; }
    
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}